#Numpy

In [1]:
import numpy as np
x1=np.array(55)
print(x1)
print(type(x1))
print(x1.shape)

55
<class 'numpy.ndarray'>
()


###1D array

In [12]:
x2=np.array([1,2,3,4,5,6,7,8,9])
print(x2)
print(type(x2))
print(x2.ndim)
print(x2.shape)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(9,)


In [5]:
print(np.__version__)

1.26.4


##User input

In [14]:
str=print(input("Enter the Nmae:"))
print(str)

Enter the Nmae: NAYAN


NAYAN
None


##2D array or matrix

In [16]:
x3=np.array([[1,2,3],[5,6,7]])
print(x3)
print(type(x3))
print(x3.ndim)
print(x3.shape)

[[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>
2
(2, 3)


##3D array

x4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x4)
print(type(x4))
print(x4.ndim)
print(x4.shape)

##4D ARRAY

In [18]:
x5=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
print(x5)
print(type(x5))
print(x5.ndim)
print(x5.shape)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
<class 'numpy.ndarray'>
4
(2, 2, 2, 2)


## RESNAPING OR AN ARRAY

In [20]:
x7=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x7)
print(x7.ndim)
print(x7.shape)
print("*"*30)
x6=x7.reshape(2,1,2,3)##(2,2,2),(2,4),(2,1,3,2,1)
print(x6)
print(x6.ndim)
print(x6.shape)
print("*"*30)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
******************************
[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]]
4
(2, 1, 2, 3)
******************************


# two variables eq solutions 

In [22]:
a=np.array([[4,3],[-5,3]])
b=np.array([20,96])
sol=np.linalg.solve(a,b)
print(sol)

[-8.44444444 17.92592593]


##three variables eq solutions

In [24]:
a=np.array([[12,14,-10],[20,-15,11],[15,-4,5]])
b=np.array([20,21,12])
sol=np.linalg.solve(a,b)
print(sol)

[ 1.31798246 -1.89254386 -3.06798246]


## USE CASE OF Numpy

In [26]:
from matplotlib.image import imread
hi=imread("C://Users//dell//Desktop//12.jpeg")
print(hi)
print(type(hi))
print(hi.ndim)
print(hi.shape)

[[[ 56  76  39]
  [ 56  76  39]
  [ 55  75  38]
  ...
  [ 98 104  56]
  [ 98 104  56]
  [ 97 103  57]]

 [[ 56  76  39]
  [ 56  76  39]
  [ 56  76  39]
  ...
  [ 98 106  57]
  [ 98 106  57]
  [ 97 105  58]]

 [[ 56  76  39]
  [ 56  76  39]
  [ 56  76  39]
  ...
  [ 99 107  58]
  [ 99 107  58]
  [ 98 106  59]]

 ...

 [[ 73  84  42]
  [ 73  84  42]
  [ 72  83  41]
  ...
  [ 51  61  37]
  [ 54  64  40]
  [ 51  61  24]]

 [[ 75  83  42]
  [ 75  83  42]
  [ 74  82  41]
  ...
  [ 54  63  36]
  [ 54  63  36]
  [ 52  63  23]]

 [[ 75  83  42]
  [ 75  83  42]
  [ 74  82  41]
  ...
  [ 54  63  34]
  [ 61  68  37]
  [ 54  62  21]]]
<class 'numpy.ndarray'>
3
(285, 177, 3)


##Matrix solving

In [28]:
test=np.array([[6,1,1],[-4,6,5],[2,8,7]])
print(test)
print("--"*30)
print(np.linalg.matrix_rank(test))
print("--"*30)
print(np.trace(test))
print("--"*30)
print(np.linalg.det(test))
print("--"*30)
print(np.linalg.inv(test))
print("--"*30)

[[ 6  1  1]
 [-4  6  5]
 [ 2  8  7]]
------------------------------------------------------------
3
------------------------------------------------------------
19
------------------------------------------------------------
5.999999999999992
------------------------------------------------------------
[[ 0.33333333  0.16666667 -0.16666667]
 [ 6.33333333  6.66666667 -5.66666667]
 [-7.33333333 -7.66666667  6.66666667]]
------------------------------------------------------------


##Power 

In [129]:
np.linalg.matrix_power(test,3)

array([[ 160,  298,  260],
       [-394,  882,  749],
       [-278, 1358, 1161]])

## eigen value

In [30]:
test1=np.array([[1,2,4],[88,7,4],[6,8,9]])
print(test1)
print()
C,d=np.linalg.eigh(test1)
print(C)
print(d)

[[ 1  2  4]
 [88  7  4]
 [ 6  8  9]]

[-84.06788609   7.84769393  93.22019217]
[[ 0.71845948  0.09099669  0.68959088]
 [-0.69543856  0.07478808  0.71468312]
 [ 0.01346062 -0.99303894  0.11701481]]


In [140]:
np.transpose(test1)

array([[ 1, 88,  6],
       [ 2,  7,  8],
       [ 4,  4,  9]])

## MEAN MODE,MIDIAN

In [32]:
from scipy import stats
speed=np.array([22,44,77,88,99,33,12,45,32,66,76,5,3,2,0,14])
m=np.mean(speed)
print(m)
m1=np.median(speed)
print(m1)
m2=stats.mode(speed)
print(m2)

38.625
32.5
ModeResult(mode=0, count=1)


In [34]:
from scipy import stats
speed=np.array([22,44,77,88,99,33,12,45,32,66,76,5,3,2,0,14])
m=np.mean(speed)
print(m)
m1=np.median(speed)
print(m1)
m2=stats.mode(speed)
print(m2)

38.625
32.5
ModeResult(mode=0, count=1)


##SD, varience

In [39]:
speed=np.array([22,33,44,11,66,88,77,99,66,55,6])
print(speed.std())
print(speed.var())

29.619906194571357
877.3388429752066


##percentile 

In [44]:
speed=np.array([22,33,44,11,66,88,77,99,66,55,6])
np.percentile(speed,75)

71.5